// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBXm52zTr21i5lx4Bi6rUpk7BDTJzsZc',
    appId: '1:132977314201:web:89d6bc474af5dc7ee76b08',
    messagingSenderId: '132977314201',
    projectId: 'doplsnew',
    authDomain: 'doplsnew.firebaseapp.com',
    storageBucket: 'doplsnew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMd6b79ra75MSOpyhQOnCY3IWyraZWwX8',
    appId: '1:132977314201:android:471b36910dce8660e76b08',
    messagingSenderId: '132977314201',
    projectId: 'doplsnew',
    storageBucket: 'doplsnew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCooB6CNWePc8duGElBK1-P_KW-iZX4F8U',
    appId: '1:132977314201:ios:e82ae8ea54dd9d64e76b08',
    messagingSenderId: '132977314201',
    projectId: 'doplsnew',
    storageBucket: 'doplsnew.appspot.com',
    iosBundleId: 'com.example.doplsnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCooB6CNWePc8duGElBK1-P_KW-iZX4F8U',
    appId: '1:132977314201:ios:e82ae8ea54dd9d64e76b08',
    messagingSenderId: '132977314201',
    projectId: 'doplsnew',
    storageBucket: 'doplsnew.appspot.com',
    iosBundleId: 'com.example.doplsnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVBXm52zTr21i5lx4Bi6rUpk7BDTJzsZc',
    appId: '1:132977314201:web:23608613f78f01bae76b08',
    messagingSenderId: '132977314201',
    projectId: 'doplsnew',
    authDomain: 'doplsnew.firebaseapp.com',
    storageBucket: 'doplsnew.appspot.com',
  );
}
